#import <Foundation/Foundation.h>
#import "SWGAppVersionApiResponse.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAppApi: NSObject <SWGApi>

extern NSString* kSWGAppApiErrorDomain;
extern NSInteger kSWGAppApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 查询APP版本信息
/// 
///
/// @param type APP类型(android、ios)
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGAppVersionApiResponse*
-(NSURLSessionTask*) getVersionUsingGETWithType: (NSString*) type
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGAppVersionApiResponse* output, NSError* error)) handler;



@end
