#import <Foundation/Foundation.h>
#import "SWGBureauIndustryDetailApiResponse.h"
#import "SWGCompanyAutoCompleteApiResponse.h"
#import "SWGCompanyBaseInfoApiResponse.h"
#import "SWGCompanyBranchListApiResponse.h"
#import "SWGCompanyChangeRecordListApiResponse.h"
#import "SWGCompanyDetailApiResponse.h"
#import "SWGCompanyExecutiveListApiResponse.h"
#import "SWGCompanyForeignInvestmenListApiResponse.h"
#import "SWGCompanyKpiApiResponse.h"
#import "SWGCompanyListApiResponse.h"
#import "SWGCompanyShareHolderListApiResponse.h"
#import "SWGIndustryCodeListApiResponse.h"
#import "SWGIndustryFinanceApiResponse.h"
#import "SWGPageCompany.h"
#import "SWGPageCompanyApiResponse.h"
#import "SWGSearchHotWordApiResponse.h"
#import "SWGZoneCodeListApiResponse.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGCompanyApi: NSObject <SWGApi>

extern NSString* kSWGCompanyApiErrorDomain;
extern NSInteger kSWGCompanyApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 查询全部公司列表
/// 
///
/// @param lastCompanyId The last company id
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyListApiResponse*
-(NSURLSessionTask*) getAllCompanyListUsingGETWithLastCompanyId: (NSString*) lastCompanyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyListApiResponse* output, NSError* error)) handler;


/// 查询分支机构
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyBranchListApiResponse*
-(NSURLSessionTask*) getBranchByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyBranchListApiResponse* output, NSError* error)) handler;


/// 查询公司工商详情
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGBureauIndustryDetailApiResponse*
-(NSURLSessionTask*) getBureauIndustryDetailUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGBureauIndustryDetailApiResponse* output, NSError* error)) handler;


/// 查询变更记录
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyChangeRecordListApiResponse*
-(NSURLSessionTask*) getChangeRecordByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyChangeRecordListApiResponse* output, NSError* error)) handler;


/// 公司搜索下拉提示
/// 
///
/// @param name 公司名称
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyAutoCompleteApiResponse*
-(NSURLSessionTask*) getCompanyAutoCompleteUsingGETWithName: (NSString*) name
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyAutoCompleteApiResponse* output, NSError* error)) handler;


/// 查询公司基本信息
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyBaseInfoApiResponse*
-(NSURLSessionTask*) getCompanyBaseInfoByIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyBaseInfoApiResponse* output, NSError* error)) handler;


/// 查询公司详情
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// @param username 用户名 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyDetailApiResponse*
-(NSURLSessionTask*) getCompanyDetailUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    username: (NSString*) username
    completionHandler: (void (^)(SWGCompanyDetailApiResponse* output, NSError* error)) handler;


/// 查询公司对外投资
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyForeignInvestmenListApiResponse*
-(NSURLSessionTask*) getCompanyForeignInvestmenByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyForeignInvestmenListApiResponse* output, NSError* error)) handler;


/// 查询公司指标
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyKpiApiResponse*
-(NSURLSessionTask*) getCompanyKpiByIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyKpiApiResponse* output, NSError* error)) handler;


/// 查询法人对外投资
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyForeignInvestmenListApiResponse*
-(NSURLSessionTask*) getCorporateForeignInvestmenByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyForeignInvestmenListApiResponse* output, NSError* error)) handler;


/// 查询高管信息
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyExecutiveListApiResponse*
-(NSURLSessionTask*) getExecutiveByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyExecutiveListApiResponse* output, NSError* error)) handler;


/// 查询行业分析
/// 
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGIndustryFinanceApiResponse*
-(NSURLSessionTask*) getIndustryFinanceByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGIndustryFinanceApiResponse* output, NSError* error)) handler;


/// 查询随机公司列表
/// 
///
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyListApiResponse*
-(NSURLSessionTask*) getRandomCompanyListUsingGETWithLoginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyListApiResponse* output, NSError* error)) handler;


/// 搜索热词列表
/// 
///
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGSearchHotWordApiResponse*
-(NSURLSessionTask*) getSearchHotWordsUsingGET1WithLoginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGSearchHotWordApiResponse* output, NSError* error)) handler;


/// 查询股东信息
/// The response includes the company shareholder information
///
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyShareHolderListApiResponse*
-(NSURLSessionTask*) getShareholderByCompanyIdUsingGETWithCompanyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyShareHolderListApiResponse* output, NSError* error)) handler;


/// 查询子行业
/// 
///
/// @param industryCode 行业编码(0查询一级行业)
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGIndustryCodeListApiResponse*
-(NSURLSessionTask*) getSubIndustryCodeListUsingGETWithIndustryCode: (NSString*) industryCode
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGIndustryCodeListApiResponse* output, NSError* error)) handler;


/// 查询子地区
/// 
///
/// @param zoneCode 地区编码(0查询全国省)
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGZoneCodeListApiResponse*
-(NSURLSessionTask*) getSubZoneCodeListUsingGETWithZoneCode: (NSString*) zoneCode
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGZoneCodeListApiResponse* output, NSError* error)) handler;


/// 查企业
/// 
///
/// @param name 公司名称/产品
/// @param pageNumber 页数
/// @param pageSize 每页数量
/// @param loginToken 登录令牌 (optional)
/// @param industryCode 行业代码 (optional)
/// @param zoneCode 地区代码 (optional)
/// @param revenueScope 收入 (optional)
/// 
///  code:200 message:"successful operation",
///  code:400 message:"Invalid name supplied",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPageCompanyApiResponse*
-(NSURLSessionTask*) queryCompanyListByNameUsingGETWithName: (NSString*) name
    pageNumber: (NSNumber*) pageNumber
    pageSize: (NSNumber*) pageSize
    loginToken: (NSString*) loginToken
    industryCode: (NSString*) industryCode
    zoneCode: (NSString*) zoneCode
    revenueScope: (NSString*) revenueScope
    completionHandler: (void (^)(SWGPageCompanyApiResponse* output, NSError* error)) handler;


/// 我要卖
/// 
///
/// @param product 产品名称
/// @param pageNumber 页数
/// @param pageSize 每页数量
/// @param loginToken 登录令牌 (optional)
/// @param industryCode 行业代码 (optional)
/// @param zoneCode 地区代码 (optional)
/// 
///  code:200 message:"successful operation",
///  code:400 message:"Invalid name supplied",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPageCompanyApiResponse*
-(NSURLSessionTask*) queryWantBuyCompanyListByProductUsingGETWithProduct: (NSString*) product
    pageNumber: (NSNumber*) pageNumber
    pageSize: (NSNumber*) pageSize
    loginToken: (NSString*) loginToken
    industryCode: (NSString*) industryCode
    zoneCode: (NSString*) zoneCode
    completionHandler: (void (^)(SWGPageCompanyApiResponse* output, NSError* error)) handler;



@end
