#import <Foundation/Foundation.h>
#import "SWGVoucherGroupListApiResponse.h"
#import "SWGVoucherListApiResponse.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGVoucherApi: NSObject <SWGApi>

extern NSString* kSWGVoucherApiErrorDomain;
extern NSInteger kSWGVoucherApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 抵用券组列表
/// 
///
/// @param username 用户名
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGVoucherGroupListApiResponse*
-(NSURLSessionTask*) getAvailableVoucherGroupsUsingGETWithUsername: (NSString*) username
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGVoucherGroupListApiResponse* output, NSError* error)) handler;


/// 抵用券列表
/// 
///
/// @param username 用户名
/// @param type 类型(1会员  2报告)
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGVoucherListApiResponse*
-(NSURLSessionTask*) getAvailableVouchersUsingGETWithUsername: (NSString*) username
    type: (NSString*) type
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGVoucherListApiResponse* output, NSError* error)) handler;



@end
