#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCompanyBaseInfo.h"
#import "SWGCompanyBranch.h"
#import "SWGCompanyChangeRecord.h"
#import "SWGCompanyExecutive.h"
#import "SWGCompanyForeignInvestmen.h"
#import "SWGCompanyShareHolder.h"
#import "SWGPhoneClue.h"
@protocol SWGCompanyBaseInfo;
@class SWGCompanyBaseInfo;
@protocol SWGCompanyBranch;
@class SWGCompanyBranch;
@protocol SWGCompanyChangeRecord;
@class SWGCompanyChangeRecord;
@protocol SWGCompanyExecutive;
@class SWGCompanyExecutive;
@protocol SWGCompanyForeignInvestmen;
@class SWGCompanyForeignInvestmen;
@protocol SWGCompanyShareHolder;
@class SWGCompanyShareHolder;
@protocol SWGPhoneClue;
@class SWGPhoneClue;



@protocol SWGBureauIndustryDetailApiResponse
@end

@interface SWGBureauIndustryDetailApiResponse : SWGObject


@property(nonatomic) NSNumber* code;
/* 公司基本信息 [optional]
 */
@property(nonatomic) SWGCompanyBaseInfo* companyBaseInfo;
/* 分支机构 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyBranch>* companyBranchList;
/* 变更记录 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyChangeRecord>* companyChangeRecordList;
/* 公司对外投资 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyForeignInvestmen>* companyCompanyForeignInvestmenList;
/* 法人对外投资 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyForeignInvestmen>* companyCorporateForeignInvestmenList;
/* 高管信息 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyExecutive>* companyExecutiveList;
/* 股东 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyShareHolder>* companyShareHolderList;

@property(nonatomic) NSString* message;
/* 联系方式 [optional]
 */
@property(nonatomic) NSArray<SWGPhoneClue>* phoneClueList;

@end
