#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompanyClue
@end

@interface SWGCompanyClue : SWGObject

/* 线索数量 [optional]
 */
@property(nonatomic) NSNumber* clueNumber;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* legalRepresentative;
/* 收入范围 [optional]
 */
@property(nonatomic) NSString* revenueScope;
/* 地区 [optional]
 */
@property(nonatomic) NSString* zone;

@end
