#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompanyChangeRecord
@end

@interface SWGCompanyChangeRecord : SWGObject

/* 变更后 [optional]
 */
@property(nonatomic) NSString* afterChange;
/* 变更后 [optional]
 */
@property(nonatomic) NSString* beforeChange;
/* 变更日期 [optional]
 */
@property(nonatomic) NSString* changeDate;
/* 变更类型 [optional]
 */
@property(nonatomic) NSString* type;

@end
