#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCreateClue
@end

@interface SWGCreateClue : SWGObject

/* 线索内容 
 */
@property(nonatomic) NSString* content;
/* 线索名称 
 */
@property(nonatomic) NSString* name;
/* 产品图片 [optional]
 */
@property(nonatomic) NSString* productImages;
/* 自己可见 
 */
@property(nonatomic) NSNumber* selfVisible;
/* 线索类型(1销售线索、2供应线索) 
 */
@property(nonatomic) NSString* type;
/* 有效期 
 */
@property(nonatomic) NSString* validity;
/* 地区代码 
 */
@property(nonatomic) NSString* zoneCode;
/* 地区名称 
 */
@property(nonatomic) NSString* zoneName;

@end
