#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCompanyBaseInfo.h"
#import "SWGCompanyKpi.h"
@protocol SWGCompanyBaseInfo;
@class SWGCompanyBaseInfo;
@protocol SWGCompanyKpi;
@class SWGCompanyKpi;



@protocol SWGCompanyDetailApiResponse
@end

@interface SWGCompanyDetailApiResponse : SWGObject


@property(nonatomic) NSNumber* code;
/* 公司基本信息 [optional]
 */
@property(nonatomic) SWGCompanyBaseInfo* companyBaseInfo;
/* 公司指标 [optional]
 */
@property(nonatomic) SWGCompanyKpi* companyKpi;

@property(nonatomic) NSString* message;

@end
