#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGPerson.h"
@protocol SWGPerson;
@class SWGPerson;



@protocol SWGCompanyAndClue
@end

@interface SWGCompanyAndClue : SWGObject

/* 公司经营范围 [optional]
 */
@property(nonatomic) NSString* business;
/* 公司或线索ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 索引类型(1:公司、2:线索) [optional]
 */
@property(nonatomic) NSNumber* indexType;
/* 公司法定代表人 [optional]
 */
@property(nonatomic) NSString* legalRepresentative;
/* 公司或线索名称 [optional]
 */
@property(nonatomic) NSString* name;
/* 线索人员信息 [optional]
 */
@property(nonatomic) SWGPerson* person;
/* 线索产品图片 [optional]
 */
@property(nonatomic) NSString* productImages;
/* 公司产品 [optional]
 */
@property(nonatomic) NSString* products;
/* 线索发布时间 [optional]
 */
@property(nonatomic) NSString* publishTime;
/* 公司注册时间 [optional]
 */
@property(nonatomic) NSString* regDate;
/* 公司收入范围 [optional]
 */
@property(nonatomic) NSString* revenueScope;
/* 公司标签(多个标签分号分割) [optional]
 */
@property(nonatomic) NSString* tags;
/* 线索类型 [optional]
 */
@property(nonatomic) NSString* type;
/* 线索访问量 [optional]
 */
@property(nonatomic) NSNumber* visitNum;
/* 公司或线索地区 [optional]
 */
@property(nonatomic) NSString* zone;

@end
