#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompany
@end

@interface SWGCompany : SWGObject

/* 经营范围 [optional]
 */
@property(nonatomic) NSString* business;
/* 销售线索数量 [optional]
 */
@property(nonatomic) NSNumber* clueNum;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 法定代表人 [optional]
 */
@property(nonatomic) NSString* legalRepresentative;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* name;
/* 产品 [optional]
 */
@property(nonatomic) NSString* products;
/* 注册时间 [optional]
 */
@property(nonatomic) NSString* regDate;
/* 收入范围 [optional]
 */
@property(nonatomic) NSString* revenueScope;
/* 标签(多个标签分号分割) [optional]
 */
@property(nonatomic) NSString* tags;
/* 地区 [optional]
 */
@property(nonatomic) NSString* zone;

@end
