#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompanyForeignInvestmen
@end

@interface SWGCompanyForeignInvestmen : SWGObject

/* 认缴金额 [optional]
 */
@property(nonatomic) NSString* capital;
/* 出资比例 [optional]
 */
@property(nonatomic) NSString* capitalContributionRatio;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 法人代表 [optional]
 */
@property(nonatomic) NSString* legalPerson;
/* 开业时间 [optional]
 */
@property(nonatomic) NSString* openDate;
/* 企业状态 [optional]
 */
@property(nonatomic) NSString* operStatus;

@end
