#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGClue.h"
@protocol SWGClue;
@class SWGClue;



@protocol SWGFollow
@end

@interface SWGFollow : SWGObject

/* 经营范围 [optional]
 */
@property(nonatomic) NSString* business;
/* 线索 [optional]
 */
@property(nonatomic) SWGClue* clue;
/* 线索ID [optional]
 */
@property(nonatomic) NSString* clueId;
/* 销售线索数量 [optional]
 */
@property(nonatomic) NSNumber* clueNum;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* createTime;
/* ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 法定代表人 [optional]
 */
@property(nonatomic) NSString* legalRepresentative;
/* 产品 [optional]
 */
@property(nonatomic) NSString* products;
/* 注册时间 [optional]
 */
@property(nonatomic) NSString* regDate;
/* 收入范围 [optional]
 */
@property(nonatomic) NSString* revenueScope;
/* 标签 [optional]
 */
@property(nonatomic) NSString* tags;
/* 地区 [optional]
 */
@property(nonatomic) NSString* zone;

@end
