#import <Foundation/Foundation.h>
#import "SWGPayApiResponse.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGPayApi: NSObject <SWGApi>

extern NSString* kSWGPayApiErrorDomain;
extern NSInteger kSWGPayApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 获取订单支付信息
/// 
///
/// @param username 用户名
/// @param orderId 订单编号
/// @param type 支付类型(1微信扫码、2微信APP、3支付宝扫码、4支付宝APP)
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPayApiResponse*
-(NSURLSessionTask*) getPayOrderInfoUsingGETWithUsername: (NSString*) username
    orderId: (NSString*) orderId
    type: (NSNumber*) type
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGPayApiResponse* output, NSError* error)) handler;



@end
