#import <Foundation/Foundation.h>
#import "SWGBusinessMatchDegreeApiResponse.h"
#import "SWGCompanyListApiResponse.h"
#import "SWGPageCompanyApiResponse.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGRecommendApi: NSObject <SWGApi>

extern NSString* kSWGRecommendApiErrorDomain;
extern NSInteger kSWGRecommendApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 获取相似客户列表
/// 
///
/// @param username 用户名
/// @param companyId 公司ID
/// @param pageNumber 页数
/// @param pageSize 每页条数
/// @param loginToken 登录令牌 (optional)
/// @param zoneCode 地区 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPageCompanyApiResponse*
-(NSURLSessionTask*) getAlikeCompanyListUsingGETWithUsername: (NSString*) username
    companyId: (NSString*) companyId
    pageNumber: (NSNumber*) pageNumber
    pageSize: (NSNumber*) pageSize
    loginToken: (NSString*) loginToken
    zoneCode: (NSString*) zoneCode
    completionHandler: (void (^)(SWGPageCompanyApiResponse* output, NSError* error)) handler;


/// 获取业务匹配度
/// 
///
/// @param username 用户名
/// @param companyId 公司ID
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGBusinessMatchDegreeApiResponse*
-(NSURLSessionTask*) getBusinessMatchDegreeUsingGETWithUsername: (NSString*) username
    companyId: (NSString*) companyId
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGBusinessMatchDegreeApiResponse* output, NSError* error)) handler;


/// 获取推荐列表
/// 
///
/// @param username 用户名
/// @param loginToken 登录令牌 (optional)
/// 
///  code:200 message:"successful operation",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCompanyListApiResponse*
-(NSURLSessionTask*) getRecommendListUsingGETWithUsername: (NSString*) username
    loginToken: (NSString*) loginToken
    completionHandler: (void (^)(SWGCompanyListApiResponse* output, NSError* error)) handler;



@end
