#import <Foundation/Foundation.h>
#import "SWGDefaultApiResponse.h"
#import "SWGSendVerificationCode.h"
#import "SWGApi.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSmsApi: NSObject <SWGApi>

extern NSString* kSWGSmsApiErrorDomain;
extern NSInteger kSWGSmsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 发送短信验证码
/// 返回验证码发送状态
///
/// @param sendVerificationCode 发送短信验证码信息
/// 
///  code:200 message:"successful operation",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGDefaultApiResponse*
-(NSURLSessionTask*) sendVerificationCodeUsingPOSTWithSendVerificationCode: (SWGSendVerificationCode*) sendVerificationCode
    completionHandler: (void (^)(SWGDefaultApiResponse* output, NSError* error)) handler;



@end
