#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGAppPayParam
@end

@interface SWGAppPayParam : SWGObject

/* 随机字符串 [optional]
 */
@property(nonatomic) NSString* nonceStr;
/* 预支付ID [optional]
 */
@property(nonatomic) NSString* partnerId;
/* 包 [optional]
 */
@property(nonatomic) NSString* pkg;
/* 预支付ID [optional]
 */
@property(nonatomic) NSString* prepayId;
/* 签名 [optional]
 */
@property(nonatomic) NSString* sign;
/* 时间戳 [optional]
 */
@property(nonatomic) NSString* timeStamp;

@end
