#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompanyBaseInfo
@end

@interface SWGCompanyBaseInfo : SWGObject

/* 经营范围 [optional]
 */
@property(nonatomic) NSString* business;
/* 行业代码 [optional]
 */
@property(nonatomic) NSString* industryCode;
/* 行业名称 [optional]
 */
@property(nonatomic) NSString* industryName;
/* 法定代表人 [optional]
 */
@property(nonatomic) NSString* legalRepresentative;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* name;
/* 营业期限 [optional]
 */
@property(nonatomic) NSString* operTerm;
/* 注册地址 [optional]
 */
@property(nonatomic) NSString* regAddress;
/* 注册金额 [optional]
 */
@property(nonatomic) NSString* regCapital;
/* 注册号 [optional]
 */
@property(nonatomic) NSString* regCodeComm;
/* 注册日期 [optional]
 */
@property(nonatomic) NSString* regDate;
/* 登记状态 [optional]
 */
@property(nonatomic) NSString* regStatus;
/* 公司类型 [optional]
 */
@property(nonatomic) NSString* type;
/* 公司主页 [optional]
 */
@property(nonatomic) NSString* website;
/* 地区 [optional]
 */
@property(nonatomic) NSString* zone;

@end
