#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCompanyKpi
@end

@interface SWGCompanyKpi : SWGObject

/* 总线索数量 [optional]
 */
@property(nonatomic) NSNumber* clueNum;
/* 客户线索数量 [optional]
 */
@property(nonatomic) NSNumber* customerClueNum;
/* 采购话语权评级 [optional]
 */
@property(nonatomic) NSNumber* discoursePowerGrade;
/* 企业成长力 [optional]
 */
@property(nonatomic) NSNumber* enterpriseGrowthForceGrade;
/* 电话线索数量 [optional]
 */
@property(nonatomic) NSNumber* phoneClueNum;
/* 价格敏感度评级 [optional]
 */
@property(nonatomic) NSNumber* priceSensitivityGrade;
/* 采购预测值 [optional]
 */
@property(nonatomic) NSNumber* procurementBudget;
/* 采购预测评级 [optional]
 */
@property(nonatomic) NSNumber* procurementBudgetGrade;
/* 产品 [optional]
 */
@property(nonatomic) NSString* products;
/* 收入范围 [optional]
 */
@property(nonatomic) NSString* revenueScope;
/* 供应商线索数量 [optional]
 */
@property(nonatomic) NSNumber* supplierClueNum;
/* 标签 [optional]
 */
@property(nonatomic) NSString* tags;

@end
