#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIndustryFinanceKpi.h"
#import "SWGProvinceIndustryFinanceKpi.h"
@protocol SWGIndustryFinanceKpi;
@class SWGIndustryFinanceKpi;
@protocol SWGProvinceIndustryFinanceKpi;
@class SWGProvinceIndustryFinanceKpi;



@protocol SWGIndustryFinance
@end

@interface SWGIndustryFinance : SWGObject

/* 企业性质 [optional]
 */
@property(nonatomic) NSString* enterpriseNature;
/* 行业财务指标 [optional]
 */
@property(nonatomic) NSArray<SWGIndustryFinanceKpi>* industryFinanceKpiList;
/* 行业名称 [optional]
 */
@property(nonatomic) NSString* industryName;
/* 省行业财务指标 [optional]
 */
@property(nonatomic) NSArray<SWGProvinceIndustryFinanceKpi>* provinceIndustryFinanceKpiList;
/* 地区名称 [optional]
 */
@property(nonatomic) NSString* zoneName;

@end
