#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGLogin
@end

@interface SWGLogin : SWGObject

/* 客户端信息 [optional]
 */
@property(nonatomic) NSString* clientInfo;
/* 客户端类型 
 */
@property(nonatomic) NSString* clientType;
/* 设备ID 
 */
@property(nonatomic) NSString* deviceId;
/* 密码 [optional]
 */
@property(nonatomic) NSString* password;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;

@end
