#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGModifyPerson
@end

@interface SWGModifyPerson : SWGObject

/* 所属公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 所属公司 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 部门 [optional]
 */
@property(nonatomic) NSString* department;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 职位 [optional]
 */
@property(nonatomic) NSString* job;
/* 姓名 [optional]
 */
@property(nonatomic) NSString* name;
/* 人员ID [optional]
 */
@property(nonatomic) NSString* pid;
/* 微信 [optional]
 */
@property(nonatomic) NSString* wechat;

@end
