#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGModifyPassword
@end

@interface SWGModifyPassword : SWGObject

/* 密码 
 */
@property(nonatomic) NSString* password;
/* 用户名 
 */
@property(nonatomic) NSString* username;
/* 验证码 
 */
@property(nonatomic) NSNumber* verificationCode;

@end
