#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGModifyPersonWork
@end

@interface SWGModifyPersonWork : SWGObject

/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 
 */
@property(nonatomic) NSString* companyName;
/* 部门 [optional]
 */
@property(nonatomic) NSString* department;
/* 结束时间 
 */
@property(nonatomic) NSString* etime;
/* ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 职位 [optional]
 */
@property(nonatomic) NSString* job;
/* 开始时间 
 */
@property(nonatomic) NSString* stime;

@end
