#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNotifycation
@end

@interface SWGNotifycation : SWGObject

/* 主体 [optional]
 */
@property(nonatomic) NSObject* body;
/* 创建时间 [optional]
 */
@property(nonatomic) NSString* createTime;
/* 显示类型 [optional]
 */
@property(nonatomic) NSString* displayType;
/* 通知ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 已读标志 [optional]
 */
@property(nonatomic) NSNumber* readFlag;

@end
