#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAppPayParam.h"
@protocol SWGAppPayParam;
@class SWGAppPayParam;



@protocol SWGOrder
@end

@interface SWGOrder : SWGObject

/* 金额 [optional]
 */
@property(nonatomic) NSNumber* amount;
/* APP支付参数 [optional]
 */
@property(nonatomic) SWGAppPayParam* appPayParam;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 创建时间 [optional]
 */
@property(nonatomic) NSString* createTime;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 订单编号 [optional]
 */
@property(nonatomic) NSString* _id;
/* 发票状态 [optional]
 */
@property(nonatomic) NSString* invoiceStatus;
/* 支付金额 [optional]
 */
@property(nonatomic) NSNumber* payAmount;
/* 支付状态 [optional]
 */
@property(nonatomic) NSString* payStatus;
/* 报告下载地址 [optional]
 */
@property(nonatomic) NSString* reportDownLoadUrl;
/* 订单内容 [optional]
 */
@property(nonatomic) NSString* type;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;
/* 抵用券ID [optional]
 */
@property(nonatomic) NSString* voucherId;

@end
