#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGOrderInvoice
@end

@interface SWGOrderInvoice : SWGObject

/* 银行卡账号 [optional]
 */
@property(nonatomic) NSString* accountNumber;
/* 金额 [optional]
 */
@property(nonatomic) NSNumber* amount;
/* 公司地址 [optional]
 */
@property(nonatomic) NSString* companyAddress;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 公司电话 [optional]
 */
@property(nonatomic) NSString* companyPhone;
/* 开户银行 [optional]
 */
@property(nonatomic) NSString* depositBank;
/* 一般纳税人 [optional]
 */
@property(nonatomic) NSString* generalTaxpayer;
/* 订单发票ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 发票邮寄地址 [optional]
 */
@property(nonatomic) NSString* mailAddress;
/* 收件人姓名 [optional]
 */
@property(nonatomic) NSString* receiverName;
/* 收件人手机 [optional]
 */
@property(nonatomic) NSString* receiverPhone;
/* 开票状态 0未开票 1申请成功 2已开票 [optional]
 */
@property(nonatomic) NSString* status;
/* 税务登记号 [optional]
 */
@property(nonatomic) NSString* taxId;
/* 发票类型 [optional]
 */
@property(nonatomic) NSString* type;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;
/* 邮编 [optional]
 */
@property(nonatomic) NSString* zipCode;

@end
