#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGClue.h"
#import "SWGPerson.h"
@protocol SWGClue;
@class SWGClue;
@protocol SWGPerson;
@class SWGPerson;



@protocol SWGPersonDetail
@end

@interface SWGPersonDetail : SWGObject

/* 线索列表 [optional]
 */
@property(nonatomic) NSArray<SWGClue>* clueList;
/* 人员信息 [optional]
 */
@property(nonatomic) SWGPerson* person;

@end
