#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGPerson
@end

@interface SWGPerson : SWGObject

/* 认证状态 [optional]
 */
@property(nonatomic) NSString* authStatus;
/* 名片盒存在标志 [optional]
 */
@property(nonatomic) NSNumber* cardboxExistFlag;
/* 公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 公司名称 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 部门 [optional]
 */
@property(nonatomic) NSString* department;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 投递状态 [optional]
 */
@property(nonatomic) NSNumber* handStatus;
/* 职位 [optional]
 */
@property(nonatomic) NSString* job;
/* 手机 [optional]
 */
@property(nonatomic) NSString* mobile;
/* 姓名 [optional]
 */
@property(nonatomic) NSString* name;
/* 人员ID [optional]
 */
@property(nonatomic) NSString* pid;
/* 头像 [optional]
 */
@property(nonatomic) NSString* profilePhoto;
/* 微信 [optional]
 */
@property(nonatomic) NSString* wechat;

@end
