#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGProvinceIndustryFinanceKpi
@end

@interface SWGProvinceIndustryFinanceKpi : SWGObject

/* 企业数量 [optional]
 */
@property(nonatomic) NSNumber* numOfCompany;
/* 收入总额 [optional]
 */
@property(nonatomic) NSNumber* operationRevenue;
/* 省名 [optional]
 */
@property(nonatomic) NSString* provinceName;
/* 利润总额 [optional]
 */
@property(nonatomic) NSNumber* salesProfit;

@end
