#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGPerson.h"
@protocol SWGPerson;
@class SWGPerson;



@protocol SWGPagePerson
@end

@interface SWGPagePerson : SWGObject

/* 页数 [optional]
 */
@property(nonatomic) NSNumber* pageNum;
/* 每页数量 [optional]
 */
@property(nonatomic) NSNumber* pageSize;
/* 人员列表 [optional]
 */
@property(nonatomic) NSArray<SWGPerson>* personList;
/* 总记录数 [optional]
 */
@property(nonatomic) NSNumber* total;

@end
