#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCompanyClue.h"
#import "SWGPhoneClue.h"
@protocol SWGCompanyClue;
@class SWGCompanyClue;
@protocol SWGPhoneClue;
@class SWGPhoneClue;



@protocol SWGSupplychainApiResponse
@end

@interface SWGSupplychainApiResponse : SWGObject


@property(nonatomic) NSNumber* code;
/* 客户线索 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyClue>* customerClues;

@property(nonatomic) NSString* message;
/* 电话线索 [optional]
 */
@property(nonatomic) NSArray<SWGPhoneClue>* phoneClues;
/* 供应商线索 [optional]
 */
@property(nonatomic) NSArray<SWGCompanyClue>* supplierClues;

@end
