#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGUser
@end

@interface SWGUser : SWGObject

/* 认证状态(0未认证、1待审核、2己认证) [optional]
 */
@property(nonatomic) NSString* authStatus;
/* 所属公司ID [optional]
 */
@property(nonatomic) NSString* companyId;
/* 所属公司 [optional]
 */
@property(nonatomic) NSString* companyName;
/* 创建时间 [optional]
 */
@property(nonatomic) NSString* createTime;
/* 教育经历 [optional]
 */
@property(nonatomic) NSString* educationExperience;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 性别(0女 1男) [optional]
 */
@property(nonatomic) NSNumber* gender;
/* ID [optional]
 */
@property(nonatomic) NSString* _id;
/* 行业ID [optional]
 */
@property(nonatomic) NSString* industryId;
/* 行业名称 [optional]
 */
@property(nonatomic) NSString* industryName;
/* 职位 [optional]
 */
@property(nonatomic) NSString* job;
/* 姓名 [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) NSString* password;
/* 1VIP会员 2普通用户 [optional]
 */
@property(nonatomic) NSNumber* roleId;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;
/* 会员有效期 [optional]
 */
@property(nonatomic) NSString* vipDueDate;
/* 工作经历 [optional]
 */
@property(nonatomic) NSString* workExperience;
/* 所属地区ID [optional]
 */
@property(nonatomic) NSString* zoneId;
/* 所属地区 [optional]
 */
@property(nonatomic) NSString* zoneName;

@end
