#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 领商-对外开放服务API
* 提供领商对外开放服务所有Restful接口
*
* OpenAPI spec version: 1.0.0
* Contact: ys@ibizplus.cn
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGVoucherGroup
@end

@interface SWGVoucherGroup : SWGObject

/* 金额 [optional]
 */
@property(nonatomic) NSNumber* amount;
/* 数量 [optional]
 */
@property(nonatomic) NSNumber* count;
/* 到期日期 [optional]
 */
@property(nonatomic) NSString* dueDate;
/* 类型 0-通用 1-报告 2-VIP会员 [optional]
 */
@property(nonatomic) NSString* type;

@end
